server:
  port: 8024
  
#spring:
# datasource:
#  url: jdbc:mysql://localhost:3306/t1
#  username : root
#  password : 1234
#  driver-class-name: com.mysql.cj.jdbc.Driver








# DataSource
# spring.datasource.url=jdbc:mysql://localhost:3306/t1?autoReconnect=true
# spring.datasource.username=root
# spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#